### ISSUE TITLE
How to Paginate the Query

### ISSUE THREAD

**Issue by ramneekkashyap9** [firebase/friendlyeats-ios#138]
I using this example but I am not able to paginate the data. Can you please assist me to get data filtered or not filtered to be paginated.
I am getting the pagination examples without filter feature

**Comment by ramneekkashyap9** [comment]
@mbleigh @jeremydurham @sheepmaster @domesticmouse I am looking for the help here. Please provide the guidance. thank you

**Comment by morganchen12** [comment]
This example doesn't show pagination. See [this guide](https://firebase.google.com/docs/firestore/query-data/query-cursors) in our docs instead.
