### ISSUE TITLE
Codelab Typo

### ISSUE THREAD

**Issue by jerrytdev** [firebase/friendlyeats-ios#17]
The Codelab instructions, codelab-complete branch, and quickstart-ios repo have three slightly different versions of one line; the one in the instructions does not compile.

In the [Codelab instructions](https://codelabs.developers.google.com/codelabs/firestore-ios/#6 )  this line is giving a build error of 

> Value of optional type '[String : Any]?' must be unwrapped to a value of type '[String : Any]':

`guard` let restaurant = Restaurant(dictionary: restaurantSnapshot.data()) else {`

The codelab-complete branch states
```
guard let data = restaurantSnapshot.data(),
let restaurant = Restaurant(dictionary: data) else {
```

The quickstart-ios repo uses a flatmap and an init:
`      guard let restaurant = restaurantSnapshot.data().flatMap(Restaurant.init(dictionary:)) else {`

**Comment by morganchen12** [comment]
Fixed and republished; the fix should be available soon.

Thanks for reporting!
