### ISSUE TITLE
The xcworkspace name is incorrect.

### ISSUE THREAD

**Issue by masakipedia** [firebase/friendlyeats-ios#18]
https://codelabs.developers.google.com/codelabs/firestore-ios/index.html?index=..%2F..%2Findex#2

The above URL is written
```
Open FireEats.xcworkspace in Xcode and run it (Cmd+R).
```
, but correctly
```
Open FriendlyEats.xcworkspace in Xcode and run it (Cmd+R).
```
Is not it?
I got it soon, but I reported it just in case.

**Comment by morganchen12** [comment]
Fixed, thanks for reporting!
