### ISSUE TITLE
Project still brings a lot of issues

### ISSUE THREAD

**Issue by antonijap** [firebase/friendlyeats-ios#2]
I am following a tutorial, and I am on step 3. Simple stuff but my Xcode is on fire. I think easiest is to to show you my screen.

![image](https://user-images.githubusercontent.com/12565719/31926053-1ee49d82-b895-11e7-80e6-964581878f6e.png)

**Comment by morganchen12** [comment]
Those should just be `0`.

```swift
let restaurant = Restaurant(
    // ...
    ratingCount: 0,
    averageRating: 0
)
```

The codelab text has been updated. Thanks for filing!
