### ISSUE TITLE
Detect network connection

### ISSUE THREAD

**Issue by yahyatabba** [firebase/friendlyeats-ios#25]
Hello everyone,

How can we detect the connection of network when Put or Get some data in Firestore?
the error handling doesn't show anything when the connection failed or disconnect when handling data.

Thank you

**Comment by morganchen12** [comment]
Firestore doesn't fail writes without a network connection, it just makes those writes locally and then pushes them to the server when your connection is restored. What were you planning on using the network state detection for?

**Comment by yahyatabba** [comment]
for example, when adding some new data and the connection network become lost, I should catch that to show a message that the connection is lost and the process was stopped.

**Comment by morganchen12** [comment]
In this case the write doesn't fail in a way that's visible to your local app, though. Your app is able to query the new data even if it hasn't been written to the server yet.

**Comment by yahyatabba** [comment]
ok I understand, thank you 👍
