### ISSUE TITLE
GoogleUtilities

### ISSUE THREAD

**Issue by peterlbrooks** [firebase/friendlyeats-ios#29]
GoogleUtilities seems to be involved in a pod install error if I use the current podfile when following the **https://codelabs.developers.google.com/codelabs/firestore-ios/#2  sample process?

I get a GoogleUtilities build error 'GoogleUtilities/GULAppEnvironmentUtil.h' file' not found when using the friendlyeats podfile which includes:

pod 'SDWebImage'
pod 'FirebaseUI/Auth', '~> 5.0'
pod 'FirebaseUI/Google', '~> 5.0'
pod 'Firebase/Firestore'
pod 'Firebase/Core'

(uses GoogleUtilities 5.3.6)

In this case, no files exists under the Pods-GoogleUtilities folder

The app successfully builds when the following is added to the podfile:

pod 'GoogleUtilities', '<5.3.6'

**Comment by paulb777** [comment]
Try running `pod update` instead of `pod install`.

The instructions should be changed accordingly.

**Comment by morganchen12** [comment]
Fixed in the codelab instructions.
