### ISSUE TITLE
query OR

### ISSUE THREAD

**Issue by longhoang2984** [firebase/friendlyeats-ios#3]
Hi guys,

How can I query with OR value?

**Comment by morganchen12** [comment]
This isn't supported in Firestore yet. We plan on supporting this before the end of beta (I think).

**Comment by samtstern** [comment]
@morganchen12 it's on the roadmap in general but I don't think it will come by the end of Beta.

**Comment by longhoang2984** [comment]
Ok tks guys,

I hope firestore will support it 💃
