### ISSUE TITLE
Code incorrectly added in project

### ISSUE THREAD

**Issue by jpv123** [firebase/friendlyeats-ios#4]
Hi, I'm following Cloud Firestore iOS Codelab, and in step 4 the tutorial instructs to add the following lines of code to `RestaurantTableViewCell.populate(restaurant:)`:

```
nameLabel.text = restaurant.name
cityLabel.text = restaurant.city
categoryLabel.text = restaurant.category
starsView.rating = Int(restaurant.averageRating.rounded())
priceLabel.text = priceString(from: restaurant.price)
```

Project already has those lines added :) The tutorial has to be updated or those lines should be removed from the code

Greetings

**Comment by morganchen12** [comment]
Fixed in 3b2cd30444d5d5c6d9b43747c740544e317d57ec.

Thanks!
