### ISSUE TITLE
 Showing All Messages :-1: SWIFT_VERSION '3.0' is unsupported, supported versions are: 4.0, 4.2, 5.0. (in target 'FriendlyEats')

### ISSUE THREAD

**Issue by MrThiago** [firebase/friendlyeats-ios#48]
Showing All Messages
:-1: SWIFT_VERSION '3.0' is unsupported, supported versions are: 4.0, 4.2, 5.0. (in target 'FriendlyEats')

**Comment by quangtqag** [comment]
You can change Swift Language Verson into 4.2 and manually update 4 or 5 places. 
And if you get the error: _Use of undeclared type 'Timestamp'_ then you need to import **FirebaseFirestore**

**Comment by morganchen12** [comment]
Fixed in https://github.com/firebase/friendlyeats-ios/commit/063875bec87cee6400f536fb9c5bc12667cabc28.
