### ISSUE TITLE
Error: Use of undeclared type 'Timestamp'

### ISSUE THREAD

**Issue by quangtqag** [firebase/friendlyeats-ios#52]
You need to add import FirebaseFirestore into Restaurant.swift file to suppress this error.

**Comment by morganchen12** [comment]
@quangtqag I was able to build without this import. What version of CocoaPods are you using?

**Comment by quangtqag** [comment]
I am using v1.6.1

**Comment by morganchen12** [comment]
That should work fine. We can add the import anyway since it doesn't break anything.
