### ISSUE TITLE
Issue with Step 3 and Auth UI

### ISSUE THREAD

**Issue by axtonpitt** [firebase/friendlyeats-ios#65]
The current Cloud Firestore Codelab misses a crucial component on Step 3, as it does not show how to add sign in providers on the sign in screen. I was stuck for a while as to why the `AuthViewController` was blank.

I added code to the `RestaurantsTableViewController.swift` to fix this issue:

Inside `viewDidAppear(_ animated: Bool) {`

```
let actionCodeSettings = ActionCodeSettings()
    actionCodeSettings.handleCodeInApp = true
    actionCodeSettings.setIOSBundleID("your bundle id here")

    let auth = FUIAuth.defaultAuthUI()!
    let provider = FUIEmailAuth.init(authAuthUI: auth, signInMethod: EmailLinkAuthSignInMethod, forceSameDevice: false, allowNewEmailAccounts: true, actionCodeSetting: actionCodeSettings)

    if auth.auth?.currentUser == nil {
      auth.providers = [provider]
      present(auth.authViewController(), animated: true, completion: nil)
    }
```

Please update the tutorial to reflect this.

Thanks!

**Comment by morganchen12** [comment]
Fixed in 801f08b. Thanks for reporting!
